import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import java.util.Arrays;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        getJsonFile();
    }

//    public static void JSONToArrayList(Authors arrayInput){
//        Authors ArrayList<String> jsonArray = new Gson().fromJson(arrayInput.toString(),ArrayList.class);
//    }

    public static void getJsonFile(){
        Path path = Paths.get("assets/recentquotes.json");

        try(BufferedReader reader = Files.newBufferedReader(path)){
            Gson gson = new Gson();

            Authors[] jsonAuthor = gson.fromJson(reader, Authors[].class);

            System.out.println(Arrays.toString(jsonAuthor));

        }catch(IOException e){

        }




//        List<Authors> mcList = Arrays.asList(jsonAuthor);

//        List<Authors> mcList = new ArrayList<>(Arrays.asList(jsonAuthor));


    }

}
