import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import java.util.Arrays;
import java.util.Random;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        getJsonFile();
    }

    public static void getJsonFile(){
        // create a path for our json file
        Path path = Paths.get("assets/recentquotes.json");
        int storedRandom = 0;
        storedRandom = randomGenerator();
        // using BufferedReader to read path/file
        try(BufferedReader reader = Files.newBufferedReader(path)){
            Gson gson = new Gson();
            Authors[] jsonAuthor = gson.fromJson(reader, Authors[].class);
            System.out.println(Arrays.toString(jsonAuthor));
            System.out.println(jsonAuthor[storedRandom].author);
            System.out.println(jsonAuthor[storedRandom].text);
        }catch(IOException e){

        }
    }

    public static int randomGenerator(){
        Random randomNum = new Random();
        return randomNum.nextInt(10);
    }
}
