import com.google.gson.Gson;
import com.google.gson.JsonParser;

import javax.naming.Context;
import java.io.*;
import java.net.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import java.util.Arrays;
import java.util.Random;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {


        /**
         * still working on writing into the json file
         */
//        Path path = Paths.get("assets/recentquotes.json");
//        Gson gson = new Gson();
//        Authors author = new Authors("name",  "quotes" );
//        gson.toJson(author, new FileWriter(path, true));


//        getTrumpQuotes();
        getJsonFile();
    }

//    public static void getTrumpQuotes(){
//
//        try{
//            URL url = new URL("https://api.whatdoestrumpthink.com/api/v1/quotes/random");
//            HttpURLConnection con = (HttpURLConnection) url.openConnection();
//            con.setRequestMethod("GET");
//
//            System.out.println("about to send request");
////            JsonParser jp = new JsonParser();
//            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
//            System.out.println("request came back");
//            String inputLine;
//
//            StringBuffer content = new StringBuffer();
//            while ((inputLine = in.readLine()) != null){
//
//                content.append(inputLine +"\n");
//
//            }
//            System.out.println(content);
//            in.close();
//        }catch(MalformedURLException e){
//            System.out.println("FIX YO URL" + e);
//        }catch (ProtocolException e){
//            System.out.println("SEEMS LIKE SOMETHING DIDN'T COME BECK" + e);
//        }catch (IOException e){
//            System.out.println("Something came in and didn't come beck, or maybe the other way around " + e);
//        }
//    }
//


    public static void getJsonFile(){
        // create a path for our json file
        Path path = Paths.get("assets/recentquotes.json");
        int storedRandom = 0;
        storedRandom = randomGenerator();

        // using BufferedReader to read path/file
        try(BufferedReader reader = Files.newBufferedReader(path)){
            Gson gson = new Gson();
            Authors[] jsonAuthor = gson.fromJson(reader, Authors[].class);

            System.out.println(jsonAuthor[storedRandom].toString() + " Index Number: " + storedRandom);
//            System.out.println(jsonAuthor[storedRandom].text);

        }catch(IOException e){

        }
    }

    public static int randomGenerator(){
        Random randomNum = new Random();
        return randomNum.nextInt(10);
    }
}
