/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.*;

public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final ByteArrayOutputStream errContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;
    private final PrintStream originalErr = System.err;

    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
        System.setErr(new PrintStream(errContent));
    }

    @After
    public void restoreStreams() {
        System.setOut(originalOut);
        System.setErr(originalErr);
    }

    @Test
    public void testGetJsonFileContainsAuthor(){


        int storedRandom = 0;
        storedRandom = App.randomGenerator();
        Authors[] quotes = App.getJsonFile();
        System.out.println(quotes[storedRandom].toString() + " Index Number: " + storedRandom);
        String result = outContent.toString();


        assertTrue(result.contains("Author:"));
    }

    @Test
    public void testGetJsonFileContainsQuote(){


        int storedRandom = 0;
        storedRandom = App.randomGenerator();
        Authors[] quotes = App.getJsonFile();
        System.out.println(quotes[storedRandom].toString() + " Index Number: " + storedRandom);
        String result = outContent.toString();


        assertTrue(result.contains("Quote:"));
    }

    @Test
    public void testGetJsonFileContainsIndex(){

        int storedRandom = 0;
        storedRandom = App.randomGenerator();
        Authors[] quotes = App.getJsonFile();
        System.out.println(quotes[storedRandom].toString() + " Index Number: " + storedRandom);
        String result = outContent.toString();


        assertTrue(result.contains("Index Number:"));
    }

    @Test
    public void testGetTrump(){

        assertTrue(App.getTrumpQuotes().contains("Donald Trump"));
    }

    @Test
    public void testAddToJson() {

        String[] tags = new String[0];
        Authors test = new Authors(tags, "Ryan Reynolds", "3", "Lady Gaga");
        App.addToJson(test);

        assertFalse(App.addToJson(test));}





    }
